### ISSUE TITLE
No credentials provided

### ISSUE THREAD

**Issue by joseant** [jagalindo/edistribucion#3]
Hola.

He probado a añadir en custom_components los archivos del repositorio.

y luego en el configuration.yaml

```
sensor:
  - platform: edistribucion
    username: mi_usuario
    password: contraseña
```

pero en los logs indica lo siguiente:
2021-06-02 12:52:18 DEBUG (MainThread) [custom_components.edistribucion] No credentials provided
